version: '2'

services:
#  web:
#    build: .
#    ports:
#     - "5000:5000"
#    volumes:
#     - .:/code
  redis:
    image: redis
#    ports:
#      - "6379"
  elasticsearch:
    image: elasticsearch:latest
#  command: elasticsearch -Des.network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"

  mongodb:
    image: mongo
    ports:
    - "27017:27017"
